import json

SCATTERED_FISHING_AREAS = [
    # -------------------------------------------------------------
    # 1. PULICAT & TIRUVALLUR COAST
    # -------------------------------------------------------------
    {
        "id": "pfz-pulicat-bar",
        "name": "Pazhaverkadu Estuary Bar",
        "lat": 13.4352,
        "lng": 80.3518,
        "harbour": "Pulicat Landing Centre (14m Depth)",
        "dist": 5.2,
        "chl": 2.85,
        "sst": 28.8,
        "species": ["Tiger Prawn", "Mud Crab", "Mullet", "Silver Belly"],
    },
    {
        "id": "pfz-pulicat-reef",
        "name": "Pulicat North Coral Ridge",
        "lat": 13.5124,
        "lng": 80.4182,
        "harbour": "Pulicat Landing Centre (28m Depth)",
        "dist": 11.4,
        "chl": 2.45,
        "sst": 28.5,
        "species": ["Seer Fish", "Snapper", "Trevally", "Cuttlefish"],
    },
    {
        "id": "pfz-lighthouse-kuppam",
        "name": "Light House Kuppam Shoal",
        "lat": 13.3881,
        "lng": 80.3756,
        "harbour": "Pulicat Base (22m Depth)",
        "dist": 7.8,
        "chl": 2.60,
        "sst": 28.7,
        "species": ["White Shrimp", "Indian Mackerel", "Anchovy", "Crab"],
    },
    {
        "id": "pfz-pulicat-dropoff",
        "name": "Pulicat Outer Continental Drop-Off",
        "lat": 13.4655,
        "lng": 80.5621,
        "harbour": "Pulicat Outer Margin (140m Depth)",
        "dist": 22.8,
        "chl": 1.95,
        "sst": 28.3,
        "species": ["Yellowfin Tuna", "Barracuda", "Cobias", "Squid"],
    },
    {
        "id": "pfz-kattupalli-fairway",
        "name": "Kattupalli Port Deep Fairway",
        "lat": 13.3150,
        "lng": 80.5205,
        "harbour": "Ennore Port (85m Depth)",
        "dist": 16.5,
        "chl": 2.10,
        "sst": 28.4,
        "species": ["King Mackerel", "Carangids", "Ribbonfish", "Seer Fish"],
    },

    # -------------------------------------------------------------
    # 2. ENNORE & NORTH CHENNAI
    # -------------------------------------------------------------
    {
        "id": "pfz-ennore-thermal",
        "name": "Ennore Creek Thermal Front",
        "lat": 13.2384,
        "lng": 80.3652,
        "harbour": "Ennore Port (16m Depth)",
        "dist": 4.8,
        "chl": 2.75,
        "sst": 29.2,
        "species": ["Snapper", "Mullet", "White Shrimp", "Sardine"],
    },
    {
        "id": "pfz-ennore-shoal",
        "name": "Ennore Shoal Sand Bank",
        "lat": 13.2842,
        "lng": 80.4325,
        "harbour": "Ennore Port (34m Depth)",
        "dist": 9.5,
        "chl": 2.50,
        "sst": 28.8,
        "species": ["Indian Mackerel", "Seer Fish", "Squid", "Pomfret"],
    },
    {
        "id": "pfz-north-chennai-slope",
        "name": "North Chennai Deep Slope Trench",
        "lat": 13.1955,
        "lng": 80.6128,
        "harbour": "Kasimedu Outer (280m Depth)",
        "dist": 25.4,
        "chl": 1.80,
        "sst": 28.1,
        "species": ["Yellowfin Tuna", "Sailfish", "Swordfish", "Mahi Mahi"],
    },
    {
        "id": "pfz-royapuram-edge",
        "name": "Royapuram Pelagic Edge",
        "lat": 13.1425,
        "lng": 80.4108,
        "harbour": "Kasimedu Fishing Harbour (45m Depth)",
        "dist": 8.2,
        "chl": 2.40,
        "sst": 28.7,
        "species": ["Ribbonfish", "Seer Fish", "Cuttlefish", "Trevally"],
    },

    # -------------------------------------------------------------
    # 3. KASIMEDU, MARINA & CENTRAL CHENNAI
    # -------------------------------------------------------------
    {
        "id": "pfz-kasimedu-breakwater",
        "name": "Kasimedu Harbour Breakwater Ridge",
        "lat": 13.1180,
        "lng": 80.3255,
        "harbour": "Kasimedu Fishing Harbour (18m Depth)",
        "dist": 3.6,
        "chl": 2.80,
        "sst": 29.1,
        "species": ["Indian Mackerel", "Sardine", "Seer Fish", "Silver Pomfret"],
    },
    {
        "id": "pfz-marina-sandbar",
        "name": "Marina Beach Submerged Bar",
        "lat": 13.0452,
        "lng": 80.3125,
        "harbour": "Kasimedu Fishing Harbour (20m Depth)",
        "dist": 4.5,
        "chl": 2.65,
        "sst": 29.0,
        "species": ["Croaker", "Mullet", "Prawn", "Mackerel"],
    },
    {
        "id": "pfz-chennai-continental-shelf",
        "name": "Chennai Continental Shelf Break",
        "lat": 13.0850,
        "lng": 80.5402,
        "harbour": "Kasimedu Deep Sea (210m Depth)",
        "dist": 19.8,
        "chl": 1.90,
        "sst": 28.2,
        "species": ["Skipjack Tuna", "Yellowfin Tuna", "Barracuda", "Cobia"],
    },
    {
        "id": "pfz-chennai-tuna-highway",
        "name": "Chennai High Seas Tuna Highway",
        "lat": 13.0205,
        "lng": 80.6855,
        "harbour": "Kasimedu Deep Sea (450m Depth)",
        "dist": 31.0,
        "chl": 1.70,
        "sst": 27.9,
        "species": ["Bigeye Tuna", "Blue Marlin", "Sailfish", "Swordfish"],
    },

    # -------------------------------------------------------------
    # 4. ADYAR, NEELANKARAI & SOUTH CHENNAI
    # -------------------------------------------------------------
    {
        "id": "pfz-adyar-estuary",
        "name": "Adyar Estuary Plume Front",
        "lat": 12.9825,
        "lng": 80.2952,
        "harbour": "Kasimedu Base (15m Depth)",
        "dist": 6.2,
        "chl": 2.90,
        "sst": 29.3,
        "species": ["Mullet", "Tiger Prawn", "Silver Belly", "Catfish"],
    },
    {
        "id": "pfz-neelankarai-reef",
        "name": "Neelankarai Coastal Reef",
        "lat": 12.9255,
        "lng": 80.3150,
        "harbour": "Covelong / Kasimedu (25m Depth)",
        "dist": 7.5,
        "chl": 2.55,
        "sst": 28.9,
        "species": ["Snapper", "Trevally", "Seer Fish", "Squid"],
    },
    {
        "id": "pfz-uthandi-edge",
        "name": "Uthandi Offshore Edge",
        "lat": 12.8605,
        "lng": 80.3408,
        "harbour": "Covelong Base (52m Depth)",
        "dist": 10.2,
        "chl": 2.30,
        "sst": 28.6,
        "species": ["King Mackerel", "Carangids", "Barracuda", "Cuttlefish"],
    },
    {
        "id": "pfz-south-chennai-terrace",
        "name": "South Chennai Pelagic Terrace",
        "lat": 12.8950,
        "lng": 80.5105,
        "harbour": "Covelong Deep Sea (180m Depth)",
        "dist": 21.0,
        "chl": 1.85,
        "sst": 28.3,
        "species": ["Yellowfin Tuna", "Mahi Mahi", "Wahoo", "Skipjack"],
    },

    # -------------------------------------------------------------
    # 5. COVELONG (KOVALAM) & MUTTUKADU
    # -------------------------------------------------------------
    {
        "id": "pfz-covelong-reef",
        "name": "Covelong Point Rocky Reef",
        "lat": 12.7952,
        "lng": 80.2755,
        "harbour": "Covelong Fish Landing (18m Depth)",
        "dist": 3.8,
        "chl": 2.70,
        "sst": 29.0,
        "species": ["Trevally", "Barracuda", "Seer Fish", "Squid"],
    },
    {
        "id": "pfz-muttukadu-front",
        "name": "Muttukadu Estuarine Front",
        "lat": 12.8250,
        "lng": 80.2680,
        "harbour": "Covelong Fish Landing (12m Depth)",
        "dist": 2.5,
        "chl": 2.85,
        "sst": 29.2,
        "species": ["White Shrimp", "Crab", "Mullet", "Silver Pomfret"],
    },
    {
        "id": "pfz-covelong-deep-bank",
        "name": "Covelong Outer Pelagic Bank",
        "lat": 12.7550,
        "lng": 80.3855,
        "harbour": "Covelong Fish Landing (68m Depth)",
        "dist": 12.8,
        "chl": 2.25,
        "sst": 28.5,
        "species": ["King Mackerel", "Cobias", "Tuna", "Grouper"],
    },
    {
        "id": "pfz-palar-submarine-canyon",
        "name": "Palar Submarine Canyon Ridge",
        "lat": 12.7105,
        "lng": 80.5255,
        "harbour": "Covelong Deep Sea (260m Depth)",
        "dist": 23.5,
        "chl": 1.80,
        "sst": 28.2,
        "species": ["Yellowfin Tuna", "Swordfish", "Sailfish", "Mahi Mahi"],
    },

    # -------------------------------------------------------------
    # 6. MAHABALIPURAM & SADRAS
    # -------------------------------------------------------------
    {
        "id": "pfz-mahabs-shore-shoal",
        "name": "Mahabalipuram Shore Temple Shoal",
        "lat": 12.6155,
        "lng": 80.2285,
        "harbour": "Mahabalipuram Beach (16m Depth)",
        "dist": 3.2,
        "chl": 2.60,
        "sst": 28.9,
        "species": ["King Mackerel", "Snapper", "Spiny Lobster", "Sardine"],
    },
    {
        "id": "pfz-mahabs-outer-bank",
        "name": "Mahabalipuram Outer Bank",
        "lat": 12.6450,
        "lng": 80.3425,
        "harbour": "Mahabalipuram Beach (58m Depth)",
        "dist": 10.5,
        "chl": 2.20,
        "sst": 28.6,
        "species": ["Seer Fish", "Calamari", "Trevally", "Barracuda"],
    },
    {
        "id": "pfz-sadras-fort-shoal",
        "name": "Sadras Submerged Fort Shoal",
        "lat": 12.5185,
        "lng": 80.2150,
        "harbour": "Sadras Landing Center (22m Depth)",
        "dist": 4.1,
        "chl": 2.50,
        "sst": 28.8,
        "species": ["Seer Fish", "Carangids", "White Shrimp", "Snapper"],
    },
    {
        "id": "pfz-kalpakkam-upwelling",
        "name": "Kalpakkam Coastal Upwelling Zone",
        "lat": 12.4855,
        "lng": 80.3105,
        "harbour": "Sadras Landing Center (48m Depth)",
        "dist": 9.8,
        "chl": 2.35,
        "sst": 28.5,
        "species": ["Indian Mackerel", "Trevally", "Cuttlefish", "Grouper"],
    },
    {
        "id": "pfz-sadras-shelf-break",
        "name": "Sadras Continental Shelf Break",
        "lat": 12.5350,
        "lng": 80.4805,
        "harbour": "Sadras Deep Sea (310m Depth)",
        "dist": 21.2,
        "chl": 1.75,
        "sst": 28.1,
        "species": ["Yellowfin Tuna", "Bigeye Tuna", "Sailfish", "Wahoo"],
    },

    # -------------------------------------------------------------
    # 7. CHEYYUR, KADALUR & MARAKKANAM
    # -------------------------------------------------------------
    {
        "id": "pfz-kadalur-point-reef",
        "name": "Kadalur Point Rocky Reef",
        "lat": 12.3652,
        "lng": 80.1785,
        "harbour": "Cheyyur Base (24m Depth)",
        "dist": 5.6,
        "chl": 2.55,
        "sst": 28.8,
        "species": ["Snapper", "Grouper", "Reef Shark", "Squid"],
    },
    {
        "id": "pfz-cheyyur-canyon",
        "name": "Cheyyur Deepwater Canyon",
        "lat": 12.3125,
        "lng": 80.2950,
        "harbour": "Cheyyur Base (95m Depth)",
        "dist": 13.4,
        "chl": 2.15,
        "sst": 28.5,
        "species": ["Seer Fish", "Skipjack Tuna", "Barracuda", "Carangids"],
    },
    {
        "id": "pfz-marakkanam-estuary",
        "name": "Marakkanam Estuary Oyster Front",
        "lat": 12.2150,
        "lng": 80.0352,
        "harbour": "Marakkanam Estuary (15m Depth)",
        "dist": 3.5,
        "chl": 2.80,
        "sst": 29.1,
        "species": ["Silver Pomfret", "Mullet", "Shrimp", "Anchovy"],
    },
    {
        "id": "pfz-marakkanam-pelagic-edge",
        "name": "Marakkanam Pelagic High Seas Edge",
        "lat": 12.1855,
        "lng": 80.1905,
        "harbour": "Marakkanam Deep Sea (72m Depth)",
        "dist": 13.8,
        "chl": 2.20,
        "sst": 28.5,
        "species": ["Cobias", "King Mackerel", "Tuna", "Trevally"],
    },
    {
        "id": "pfz-cheyyur-abyssal-slope",
        "name": "Cheyyur Oceanic Abyssal Slope",
        "lat": 12.2450,
        "lng": 80.4205,
        "harbour": "Cheyyur Deep Sea (350m Depth)",
        "dist": 27.0,
        "chl": 1.70,
        "sst": 28.0,
        "species": ["Swordfish", "Bigeye Tuna", "Blue Marlin", "Mahi Mahi"],
    },

    # -------------------------------------------------------------
    # 8. PUDUCHERRY & CUDDALORE
    # -------------------------------------------------------------
    {
        "id": "pfz-puducherry-shoal",
        "name": "Puducherry Northern Coral Shoal",
        "lat": 11.9655,
        "lng": 79.8850,
        "harbour": "Puducherry Harbour (22m Depth)",
        "dist": 5.4,
        "chl": 2.45,
        "sst": 28.9,
        "species": ["Indian Mackerel", "Seer Fish", "Pomfret", "Squid"],
    },
    {
        "id": "pfz-puducherry-margin",
        "name": "Puducherry Continental Margin",
        "lat": 11.9150,
        "lng": 80.0255,
        "harbour": "Puducherry Harbour (110m Depth)",
        "dist": 14.8,
        "chl": 2.05,
        "sst": 28.6,
        "species": ["Yellowfin Tuna", "Sailfish", "Mahi Mahi", "Barracuda"],
    },
    {
        "id": "pfz-cuddalore-port-front",
        "name": "Cuddalore Port Coastal Fishing Ground",
        "lat": 11.7455,
        "lng": 79.8152,
        "harbour": "Cuddalore Port (18m Depth)",
        "dist": 4.2,
        "chl": 2.75,
        "sst": 29.0,
        "species": ["Indian Mackerel", "Cobia", "Squid", "Pomfret"],
    },
    {
        "id": "pfz-uppanar-outflow",
        "name": "Uppanar River Plume Front",
        "lat": 11.7105,
        "lng": 79.8550,
        "harbour": "Cuddalore Port (35m Depth)",
        "dist": 7.0,
        "chl": 2.85,
        "sst": 28.9,
        "species": ["Tiger Prawn", "Silver Belly", "Anchovy", "Carangids"],
    },
    {
        "id": "pfz-cuddalore-dropoff",
        "name": "Cuddalore Deep Sea Drop-Off",
        "lat": 11.6650,
        "lng": 80.0855,
        "harbour": "Cuddalore Port (240m Depth)",
        "dist": 19.5,
        "chl": 1.90,
        "sst": 28.3,
        "species": ["Yellowfin Tuna", "Cobia", "Spanish Mackerel", "Squid"],
    },
    {
        "id": "pfz-cuddalore-trench",
        "name": "Cuddalore High Seas Abyssal Trench",
        "lat": 11.7255,
        "lng": 80.3105,
        "harbour": "Cuddalore Deep Sea (520m Depth)",
        "dist": 31.8,
        "chl": 1.65,
        "sst": 27.9,
        "species": ["Swordfish", "Bigeye Tuna", "Sailfish", "Marlin"],
    },

    # -------------------------------------------------------------
    # 9. PORTO NOVO (PARANGIPETTAI) & COLEROON RIVER CANYON
    # -------------------------------------------------------------
    {
        "id": "pfz-portonovo-vellar",
        "name": "Vellar Estuary Plume Edge",
        "lat": 11.4985,
        "lng": 79.8125,
        "harbour": "Porto Novo Harbour (15m Depth)",
        "dist": 3.8,
        "chl": 3.10,
        "sst": 29.1,
        "species": ["Mud Crab", "Tiger Prawn", "Grouper", "Snapper"],
    },
    {
        "id": "pfz-portonovo-canyon",
        "name": "Parangipettai Submerged Canyon",
        "lat": 11.4650,
        "lng": 79.9455,
        "harbour": "Porto Novo Harbour (85m Depth)",
        "dist": 11.8,
        "chl": 2.50,
        "sst": 28.5,
        "species": ["King Mackerel", "Trevally", "Calamari", "Seer Fish"],
    },
    {
        "id": "pfz-coleroon-delta-fan",
        "name": "Coleroon River Delta Fan",
        "lat": 11.3955,
        "lng": 79.8650,
        "harbour": "Porto Novo / Poompuhar (28m Depth)",
        "dist": 6.8,
        "chl": 3.20,
        "sst": 28.8,
        "species": ["Giant Trevally", "Grouper", "Tiger Prawn", "Pomfret"],
    },
    {
        "id": "pfz-coleroon-oceanic-canyon",
        "name": "Coleroon Oceanic Canyon Trench",
        "lat": 11.3450,
        "lng": 80.0655,
        "harbour": "Poompuhar Deep Sea (310m Depth)",
        "dist": 18.2,
        "chl": 1.95,
        "sst": 28.1,
        "species": ["Yellowfin Tuna", "Bigeye Tuna", "Sailfish", "Mahi Mahi"],
    },

    # -------------------------------------------------------------
    # 10. POOMPUHAR, THARANGAMBADI & KARAIKAL
    # -------------------------------------------------------------
    {
        "id": "pfz-poompuhar-shelf",
        "name": "Poompuhar Ancient Port Shelf",
        "lat": 11.1485,
        "lng": 79.8925,
        "harbour": "Poompuhar Harbour (22m Depth)",
        "dist": 4.5,
        "chl": 2.60,
        "sst": 28.9,
        "species": ["Seer Fish", "Indian Mackerel", "Sardine", "Cuttlefish"],
    },
    {
        "id": "pfz-poompuhar-pelagic-bank",
        "name": "Poompuhar Offshore Pelagic Bank",
        "lat": 11.1850,
        "lng": 80.0250,
        "harbour": "Poompuhar Harbour (75m Depth)",
        "dist": 12.6,
        "chl": 2.25,
        "sst": 28.5,
        "species": ["Cobias", "Barracuda", "Trevally", "Squid"],
    },
    {
        "id": "pfz-tranquebar-reef",
        "name": "Tharangambadi Danish Fort Reef",
        "lat": 11.0325,
        "lng": 79.8950,
        "harbour": "Tharangambadi Landing (26m Depth)",
        "dist": 5.2,
        "chl": 2.50,
        "sst": 28.8,
        "species": ["Silver Belly", "Anchovy", "Carangids", "Shrimp"],
    },
    {
        "id": "pfz-karaikal-fairway",
        "name": "Karaikal Port Fairway Channel",
        "lat": 10.9155,
        "lng": 79.8855,
        "harbour": "Karaikal Port (20m Depth)",
        "dist": 4.8,
        "chl": 2.70,
        "sst": 28.9,
        "species": ["Indian Mackerel", "Pomfret", "Prawn", "Squid"],
    },
    {
        "id": "pfz-karaikal-margin",
        "name": "Karaikal Continental Slope",
        "lat": 10.9550,
        "lng": 80.1205,
        "harbour": "Karaikal Deep Sea (190m Depth)",
        "dist": 17.5,
        "chl": 1.95,
        "sst": 28.3,
        "species": ["Yellowfin Tuna", "Skipjack", "Seer Fish", "Calamari"],
    },
    {
        "id": "pfz-coromandel-deep-basin",
        "name": "Central Bay of Bengal Deep Terrace",
        "lat": 11.0850,
        "lng": 80.2855,
        "harbour": "Karaikal Deep Sea (480m Depth)",
        "dist": 28.5,
        "chl": 1.70,
        "sst": 28.0,
        "species": ["Bigeye Tuna", "Swordfish", "Marlin", "Sailfish"],
    },

    # -------------------------------------------------------------
    # 11. NAGORE, NAGAPATTINAM & VELANKANNI
    # -------------------------------------------------------------
    {
        "id": "pfz-nagore-coastal",
        "name": "Nagore Dargah Coastal Ground",
        "lat": 10.8250,
        "lng": 79.8850,
        "harbour": "Nagapattinam Port (18m Depth)",
        "dist": 3.8,
        "chl": 2.75,
        "sst": 28.9,
        "species": ["Silver Pomfret", "Mackerel", "Shrimp", "Mullet"],
    },
    {
        "id": "pfz-nagapattinam-harbour-edge",
        "name": "Nagapattinam Harbour Deep Entrance",
        "lat": 10.7655,
        "lng": 79.9125,
        "harbour": "Nagapattinam Port (25m Depth)",
        "dist": 4.6,
        "chl": 2.65,
        "sst": 28.7,
        "species": ["Indian Mackerel", "Seer Fish", "Squid", "Pomfret"],
    },
    {
        "id": "pfz-nagapattinam-trawl-bank",
        "name": "Nagapattinam Outer Trawl Bank",
        "lat": 10.7450,
        "lng": 80.0655,
        "harbour": "Nagapattinam Port (68m Depth)",
        "dist": 13.0,
        "chl": 2.30,
        "sst": 28.4,
        "species": ["Skipjack Tuna", "Yellowfin Tuna", "Seer Fish", "Calamari"],
    },
    {
        "id": "pfz-velankanni-shelf",
        "name": "Velankanni Basilica Marine Shelf",
        "lat": 10.6825,
        "lng": 79.8950,
        "harbour": "Velankanni Coastal Base (20m Depth)",
        "dist": 4.2,
        "chl": 2.60,
        "sst": 28.8,
        "species": ["Ribbonfish", "Pomfret", "Sardine", "Shrimp"],
    },
    {
        "id": "pfz-nagapattinam-slope",
        "name": "Nagapattinam Slope Drop-Off",
        "lat": 10.6255,
        "lng": 80.1850,
        "harbour": "Nagapattinam Deep Sea (280m Depth)",
        "dist": 20.4,
        "chl": 1.85,
        "sst": 28.1,
        "species": ["Yellowfin Tuna", "Cobias", "Barracuda", "Mahi Mahi"],
    },
    {
        "id": "pfz-nagapattinam-highway",
        "name": "Nagapattinam Deep Billfish Highway",
        "lat": 10.7105,
        "lng": 80.3955,
        "harbour": "Nagapattinam Deep Sea (610m Depth)",
        "dist": 32.5,
        "chl": 1.65,
        "sst": 27.8,
        "species": ["Bigeye Tuna", "Blue Marlin", "Swordfish", "Sailfish"],
    },

    # -------------------------------------------------------------
    # 12. POINT CALIMERE (KODIAKKARAI) & MUTHUPET
    # -------------------------------------------------------------
    {
        "id": "pfz-calimere-shoal",
        "name": "Point Calimere Upwelling Shoal",
        "lat": 10.2855,
        "lng": 79.9125,
        "harbour": "Kodiakkarai Landing (12m Depth)",
        "dist": 3.4,
        "chl": 3.10,
        "sst": 28.6,
        "species": ["Seer Fish", "Trevally", "Ray", "Crab"],
    },
    {
        "id": "pfz-kodiakkarai-bank",
        "name": "Kodiakkarai Bank Eastern Ridge",
        "lat": 10.2450,
        "lng": 80.0555,
        "harbour": "Kodiakkarai Landing (42m Depth)",
        "dist": 11.2,
        "chl": 2.50,
        "sst": 28.3,
        "species": ["Black Pomfret", "King Mackerel", "Squid", "Carangids"],
    },
    {
        "id": "pfz-calimere-submarine-ridge",
        "name": "Point Calimere Deep Submarine Ridge",
        "lat": 10.1950,
        "lng": 80.2155,
        "harbour": "Kodiakkarai Deep Sea (160m Depth)",
        "dist": 22.0,
        "chl": 1.95,
        "sst": 28.0,
        "species": ["Yellowfin Tuna", "Skipjack", "Mahi Mahi", "Barracuda"],
    },
    {
        "id": "pfz-muthupet-lagoon-bank",
        "name": "Muthupet Mangrove Outflow Bank",
        "lat": 10.3250,
        "lng": 79.5855,
        "harbour": "Mallipattinam Harbour (8m Depth)",
        "dist": 4.5,
        "chl": 3.40,
        "sst": 29.4,
        "species": ["Tiger Prawn", "Mud Crab", "Mullet", "Silver Belly"],
    },

    # -------------------------------------------------------------
    # 13. PALK STRAIT & PALK BAY SCATTERED GROUNDS
    # -------------------------------------------------------------
    {
        "id": "pfz-mallipattinam-prawn",
        "name": "Mallipattinam Prawn Shoal",
        "lat": 10.2755,
        "lng": 79.3650,
        "harbour": "Mallipattinam Harbour (6m Depth)",
        "dist": 3.2,
        "chl": 3.30,
        "sst": 29.3,
        "species": ["Tiger Prawn", "White Shrimp", "Mud Crab", "Mullet"],
    },
    {
        "id": "pfz-sethubavachatram-shoal",
        "name": "Sethubavachatram Shallow Bank",
        "lat": 10.2150,
        "lng": 79.3255,
        "harbour": "Mallipattinam Harbour (7m Depth)",
        "dist": 4.0,
        "chl": 3.20,
        "sst": 29.2,
        "species": ["Blue Swimmer Crab", "Shrimp", "Silver Belly", "Anchovy"],
    },
    {
        "id": "pfz-manamelkudi-trawl",
        "name": "Manamelkudi Shallow Trawl Flat",
        "lat": 9.9652,
        "lng": 79.2950,
        "harbour": "Kottaipattinam Harbour (9m Depth)",
        "dist": 5.0,
        "chl": 3.10,
        "sst": 29.1,
        "species": ["Blue Crab", "Penaeid Prawn", "Squid", "Mullet"],
    },
    {
        "id": "pfz-kottaipattinam-crab",
        "name": "Kottaipattinam Blue Crab Ground",
        "lat": 9.9250,
        "lng": 79.2555,
        "harbour": "Kottaipattinam Harbour (11m Depth)",
        "dist": 4.2,
        "chl": 3.05,
        "sst": 29.0,
        "species": ["Blue Swimmer Crab", "Mud Crab", "Tiger Prawn", "Ray"],
    },
    {
        "id": "pfz-palk-navigation-trench",
        "name": "Palk Strait Navigation Trench",
        "lat": 10.0855,
        "lng": 79.6250,
        "harbour": "Palk Bay Deep Channel (18m Depth)",
        "dist": 16.5,
        "chl": 2.75,
        "sst": 28.7,
        "species": ["Seer Fish", "Cuttlefish", "Carangids", "Prawn"],
    },
    {
        "id": "pfz-kottaipattinam-deep",
        "name": "Kottaipattinam Deep Channel",
        "lat": 9.8450,
        "lng": 79.4855,
        "harbour": "Kottaipattinam Harbour (14m Depth)",
        "dist": 12.0,
        "chl": 2.85,
        "sst": 28.8,
        "species": ["Seer Fish", "Indian Mackerel", "Squid", "Mullet"],
    },
    {
        "id": "pfz-mimisal-flat",
        "name": "Mimisal Coastal Mud Flat",
        "lat": 9.7855,
        "lng": 79.2150,
        "harbour": "Thondi Fish Base (8m Depth)",
        "dist": 3.6,
        "chl": 3.15,
        "sst": 29.2,
        "species": ["Shrimp", "Mullet", "Silver Belly", "Crab"],
    },
    {
        "id": "pfz-thondi-squid-ground",
        "name": "Thondi Bay Squid & Crab Ground",
        "lat": 9.7350,
        "lng": 79.0855,
        "harbour": "Thondi Fish Base (10m Depth)",
        "dist": 4.1,
        "chl": 3.00,
        "sst": 29.0,
        "species": ["Squid", "Cuttlefish", "Blue Crab", "Seer Fish"],
    },
    {
        "id": "pfz-thondi-pelagic-channel",
        "name": "Thondi Offshore Pelagic Channel",
        "lat": 9.6655,
        "lng": 79.3150,
        "harbour": "Thondi Fish Base (15m Depth)",
        "dist": 11.5,
        "chl": 2.80,
        "sst": 28.8,
        "species": ["Seer Fish", "Mackerel", "Calamari", "Trevally"],
    },
    {
        "id": "pfz-devipattinam-bay",
        "name": "Devipattinam Navagraha Bay",
        "lat": 9.5152,
        "lng": 78.9650,
        "harbour": "Devipattinam Landing (7m Depth)",
        "dist": 3.0,
        "chl": 3.20,
        "sst": 29.3,
        "species": ["Mullet", "Tiger Prawn", "Mud Crab", "Silver Belly"],
    },
    {
        "id": "pfz-palk-central-corridor",
        "name": "Palk Bay Central Marine Corridor",
        "lat": 9.6255,
        "lng": 79.5250,
        "harbour": "Pamban Outer Base (21m Depth)",
        "dist": 18.0,
        "chl": 2.65,
        "sst": 28.6,
        "species": ["Seer Fish", "Skipjack", "Squid", "Carangids"],
    },
    {
        "id": "pfz-pamban-north-reef",
        "name": "Pamban North Coral Ridge",
        "lat": 9.3255,
        "lng": 79.2450,
        "harbour": "Pamban Fishing Harbour (11m Depth)",
        "dist": 4.0,
        "chl": 2.80,
        "sst": 28.9,
        "species": ["Coral Trout", "Emperor", "Cuttlefish", "Seer Fish"],
    },
    {
        "id": "pfz-rameswaram-sangumal",
        "name": "Rameswaram Sangumal Roadstead",
        "lat": 9.3050,
        "lng": 79.3455,
        "harbour": "Rameswaram Jetty (13m Depth)",
        "dist": 3.5,
        "chl": 2.75,
        "sst": 28.8,
        "species": ["Blue Swimmer Crab", "Squid", "Grouper", "Snapper"],
    },
    {
        "id": "pfz-dhanushkodi-north",
        "name": "Dhanushkodi North Shoal Edge",
        "lat": 9.2255,
        "lng": 79.4250,
        "harbour": "Dhanushkodi Point (9m Depth)",
        "dist": 4.8,
        "chl": 2.70,
        "sst": 28.7,
        "species": ["Ray", "Trevally", "Seer Fish", "Shrimp"],
    },

    # -------------------------------------------------------------
    # 14. GULF OF MANNAR (MANDAPAM TO THOOTHUKUDI)
    # -------------------------------------------------------------
    {
        "id": "pfz-mandapam-coral-channel",
        "name": "Mandapam South Coral Reef Channel",
        "lat": 9.2455,
        "lng": 79.1650,
        "harbour": "Mandapam Harbour (14m Depth)",
        "dist": 4.2,
        "chl": 2.85,
        "sst": 28.8,
        "species": ["Seer Fish", "Cuttlefish", "Shrimp", "Mullet"],
    },
    {
        "id": "pfz-dhanushkodi-south-edge",
        "name": "Dhanushkodi South Pelagic Edge",
        "lat": 9.1250,
        "lng": 79.3855,
        "harbour": "Dhanushkodi Point (38m Depth)",
        "dist": 11.5,
        "chl": 2.40,
        "sst": 28.5,
        "species": ["Skipjack Tuna", "Trevally", "Barracuda", "Queenfish"],
    },
    {
        "id": "pfz-pamban-pass-south",
        "name": "Pamban Pass South Approach",
        "lat": 9.2150,
        "lng": 79.2855,
        "harbour": "Pamban Fishing Harbour (22m Depth)",
        "dist": 6.0,
        "chl": 2.65,
        "sst": 28.7,
        "species": ["Emperor", "Snapper", "Squid", "Mackerel"],
    },
    {
        "id": "pfz-kilakarai-appa-island",
        "name": "Kilakarai Appa Island Coral Barrier",
        "lat": 9.1852,
        "lng": 78.8450,
        "harbour": "Kilakarai Landing (16m Depth)",
        "dist": 4.8,
        "chl": 2.90,
        "sst": 28.6,
        "species": ["Grouper", "Parrotfish", "Emperor Bream", "Lobster"],
    },
    {
        "id": "pfz-valinokkam-point-bank",
        "name": "Valinokkam Point Fishing Bank",
        "lat": 9.1350,
        "lng": 78.6855,
        "harbour": "Valinokkam Port (24m Depth)",
        "dist": 5.5,
        "chl": 2.60,
        "sst": 28.6,
        "species": ["Mackerel", "Sardine", "Pomfret", "Squid"],
    },
    {
        "id": "pfz-ervadi-coastal",
        "name": "Ervadi Coastal Ground",
        "lat": 9.1755,
        "lng": 78.7450,
        "harbour": "Valinokkam Port (12m Depth)",
        "dist": 3.2,
        "chl": 2.80,
        "sst": 28.8,
        "species": ["Silver Pomfret", "Anchovy", "Prawn", "Mullet"],
    },
    {
        "id": "pfz-vembar-shelf-reef",
        "name": "Vembar Shelf Reef",
        "lat": 9.0455,
        "lng": 78.4150,
        "harbour": "Vembar Fish Landing (20m Depth)",
        "dist": 5.0,
        "chl": 2.50,
        "sst": 28.7,
        "species": ["Seer Fish", "Ribbonfish", "Anchovy", "Prawn"],
    },
    {
        "id": "pfz-vembar-pelagic-bank",
        "name": "Vembar Outer Pelagic Bank",
        "lat": 8.9450,
        "lng": 78.6255,
        "harbour": "Vembar Fish Landing (65m Depth)",
        "dist": 14.5,
        "chl": 2.25,
        "sst": 28.4,
        "species": ["Cobia", "Seer Fish", "Trevally", "Calamari"],
    },
    {
        "id": "pfz-sippikulam-shell-bed",
        "name": "Sippikulam Oyster & Shell Bed",
        "lat": 8.9655,
        "lng": 78.2850,
        "harbour": "Thoothukudi Base (15m Depth)",
        "dist": 4.5,
        "chl": 2.85,
        "sst": 28.8,
        "species": ["Mud Crab", "Prawn", "Mullet", "Snapper"],
    },
    {
        "id": "pfz-thoothukudi-hare-island",
        "name": "Thoothukudi Hare Island Coral Edge",
        "lat": 8.7950,
        "lng": 78.2155,
        "harbour": "Thoothukudi Harbour (18m Depth)",
        "dist": 3.5,
        "chl": 2.70,
        "sst": 28.7,
        "species": ["Indian Salmon", "Pomfret", "Tiger Prawn", "Squid"],
    },
    {
        "id": "pfz-thoothukudi-pearl-banks",
        "name": "Thoothukudi Deep Pearl Banks (Paars)",
        "lat": 8.7255,
        "lng": 78.3650,
        "harbour": "Thoothukudi Harbour (35m Depth)",
        "dist": 10.5,
        "chl": 2.45,
        "sst": 28.4,
        "species": ["Yellowfin Tuna", "Kingfish", "Calamari", "Snapper"],
    },
    {
        "id": "pfz-thoothukudi-slope",
        "name": "Thoothukudi Continental Slope Drop-off",
        "lat": 8.6650,
        "lng": 78.5855,
        "harbour": "Thoothukudi Harbour (180m Depth)",
        "dist": 22.0,
        "chl": 2.00,
        "sst": 28.2,
        "species": ["Swordfish", "Skipjack", "Cobia", "Yellowfin Tuna"],
    },
    {
        "id": "pfz-mannar-abyssal-trench",
        "name": "Gulf of Mannar Deep Oceanic Trench",
        "lat": 8.8250,
        "lng": 78.9455,
        "harbour": "Thoothukudi Deep Sea (520m Depth)",
        "dist": 35.0,
        "chl": 1.80,
        "sst": 27.9,
        "species": ["Bigeye Tuna", "Blue Marlin", "Swordfish", "Yellowfin Tuna"],
    },
    {
        "id": "pfz-mannar-gateway-trench",
        "name": "Mannar Abyssal Gateway Trench",
        "lat": 8.9855,
        "lng": 79.1850,
        "harbour": "Mandapam Deep Sea (380m Depth)",
        "dist": 28.5,
        "chl": 1.95,
        "sst": 28.0,
        "species": ["Sailfish", "Swordfish", "Skipjack Tuna", "Wahoo"],
    },

    # -------------------------------------------------------------
    # 15. SOUTHERN SHELF (PUNNAKAYAL TO KANYAKUMARI)
    # -------------------------------------------------------------
    {
        "id": "pfz-punnakayal-bar",
        "name": "Punnakayal Tamirabarani Estuarine Bar",
        "lat": 8.6255,
        "lng": 78.1650,
        "harbour": "Punnakayal Landing (16m Depth)",
        "dist": 3.8,
        "chl": 3.10,
        "sst": 28.6,
        "species": ["Indian Salmon", "Pomfret", "Hilsa", "Tiger Prawn"],
    },
    {
        "id": "pfz-kayalpatnam-reef",
        "name": "Kayalpatnam Outer Reef",
        "lat": 8.5750,
        "lng": 78.1955,
        "harbour": "Kayalpatnam Base (22m Depth)",
        "dist": 5.2,
        "chl": 2.65,
        "sst": 28.5,
        "species": ["Seer Fish", "Trevally", "Snapper", "Squid"],
    },
    {
        "id": "pfz-tiruchendur-shoal",
        "name": "Tiruchendur Temple Offshore Shoal",
        "lat": 8.4855,
        "lng": 78.1650,
        "harbour": "Tiruchendur Base (18m Depth)",
        "dist": 4.0,
        "chl": 2.50,
        "sst": 28.5,
        "species": ["Trevally", "Seer Fish", "Barracuda", "Squid"],
    },
    {
        "id": "pfz-manapad-headland",
        "name": "Manapad Point Rocky Headland Bank",
        "lat": 8.3650,
        "lng": 78.1155,
        "harbour": "Manapad Coastal Base (28m Depth)",
        "dist": 5.5,
        "chl": 2.45,
        "sst": 28.4,
        "species": ["Seer Fish", "Rock Cod", "Squid", "Carangids"],
    },
    {
        "id": "pfz-manapad-coral-ridge",
        "name": "Manapad Deep Coral Ridge",
        "lat": 8.3155,
        "lng": 78.2850,
        "harbour": "Manapad Coastal Base (95m Depth)",
        "dist": 14.5,
        "chl": 2.20,
        "sst": 28.2,
        "species": ["Yellowfin Tuna", "Cobia", "Grouper", "Barracuda"],
    },
    {
        "id": "pfz-kulasekharapatnam-edge",
        "name": "Kulasekharapatnam Coastal Shelf",
        "lat": 8.3955,
        "lng": 78.0750,
        "harbour": "Kulasekharapatnam (15m Depth)",
        "dist": 3.4,
        "chl": 2.55,
        "sst": 28.6,
        "species": ["Sardine", "Mackerel", "Anchovy", "Crab"],
    },
    {
        "id": "pfz-periathalai-bank",
        "name": "Periathalai Red Sand Bank",
        "lat": 8.3150,
        "lng": 77.9455,
        "harbour": "Uvari Landing (20m Depth)",
        "dist": 4.8,
        "chl": 2.40,
        "sst": 28.5,
        "species": ["Ribbonfish", "Carangids", "Mullet", "Shrimp"],
    },
    {
        "id": "pfz-uvari-rock-reef",
        "name": "Uvari Beach Rock Reef",
        "lat": 8.2755,
        "lng": 77.9150,
        "harbour": "Uvari Landing (18m Depth)",
        "dist": 3.6,
        "chl": 2.45,
        "sst": 28.4,
        "species": ["Rock Cod", "Seer Fish", "Lobster", "Prawn"],
    },
    {
        "id": "pfz-uvari-pelagic-basin",
        "name": "Uvari Offshore Pelagic Basin",
        "lat": 8.1950,
        "lng": 78.0655,
        "harbour": "Uvari Deep Sea (65m Depth)",
        "dist": 12.0,
        "chl": 2.20,
        "sst": 28.3,
        "species": ["Kingfish", "Yellowfin Tuna", "Squid", "Trevally"],
    },
    {
        "id": "pfz-idinthakarai-platform",
        "name": "Idinthakarai Shore Platform",
        "lat": 8.1755,
        "lng": 77.7850,
        "harbour": "Idinthakarai Harbour (22m Depth)",
        "dist": 4.0,
        "chl": 2.50,
        "sst": 28.3,
        "species": ["Rock Cod", "Seer Fish", "Spiny Lobster", "Tuna"],
    },
    {
        "id": "pfz-idinthakarai-outer-edge",
        "name": "Idinthakarai Outer Continental Edge",
        "lat": 8.0950,
        "lng": 77.9155,
        "harbour": "Idinthakarai Harbour (85m Depth)",
        "dist": 13.5,
        "chl": 2.25,
        "sst": 28.1,
        "species": ["Cobia", "Yellowfin Tuna", "Snapper", "Squid"],
    },

    # -------------------------------------------------------------
    # 16. KANYAKUMARI & CAPE COMORIN TRI-SEA CONVERGENCE
    # -------------------------------------------------------------
    {
        "id": "pfz-kanyakumari-cape-shoal",
        "name": "Kanyakumari Cape Point Shoal",
        "lat": 8.0755,
        "lng": 77.5850,
        "harbour": "Kanyakumari Harbour (18m Depth)",
        "dist": 3.2,
        "chl": 2.80,
        "sst": 28.1,
        "species": ["Yellowfin Tuna", "Skipjack", "Sailfish", "Mahi Mahi"],
    },
    {
        "id": "pfz-chinnamuttam-outer-basin",
        "name": "Chinnamuttam Harbour Outer Basin",
        "lat": 8.0952,
        "lng": 77.6155,
        "harbour": "Chinnamuttam Harbour (24m Depth)",
        "dist": 3.8,
        "chl": 2.75,
        "sst": 28.2,
        "species": ["Seer Fish", "Trevally", "Cuttlefish", "Grouper"],
    },
    {
        "id": "pfz-tri-sea-convergence",
        "name": "Cape Comorin Tri-Sea Convergence Ground",
        "lat": 7.9850,
        "lng": 77.6255,
        "harbour": "Kanyakumari Deep Sea (75m Depth)",
        "dist": 9.5,
        "chl": 2.90,
        "sst": 27.9,
        "species": ["Yellowfin Tuna", "Skipjack", "Sailfish", "Mahi Mahi"],
    },
    {
        "id": "pfz-indian-ocean-pelagic-ridge",
        "name": "Indian Ocean Deep Pelagic Ridge",
        "lat": 7.8455,
        "lng": 77.7150,
        "harbour": "Kanyakumari Deep Sea (240m Depth)",
        "dist": 21.0,
        "chl": 2.30,
        "sst": 27.6,
        "species": ["Bigeye Tuna", "Swordfish", "Blue Marlin", "Skipjack"],
    },

    # -------------------------------------------------------------
    # 17. WADGE BANK OCEANIC UPWELLING PLATEAU
    # -------------------------------------------------------------
    {
        "id": "pfz-wadge-northwest-shelf",
        "name": "Wadge Bank Northwest Shelf",
        "lat": 7.8855,
        "lng": 77.2150,
        "harbour": "Chinnamuttam Harbour (55m Depth)",
        "dist": 24.5,
        "chl": 3.20,
        "sst": 27.8,
        "species": ["Yellowfin Tuna", "Cobia", "Grouper", "Snapper"],
    },
    {
        "id": "pfz-wadge-core-upwelling",
        "name": "Wadge Bank Core Upwelling Ridge",
        "lat": 7.7450,
        "lng": 77.4255,
        "harbour": "Chinnamuttam Harbour (62m Depth)",
        "dist": 31.0,
        "chl": 3.45,
        "sst": 27.5,
        "species": ["Bigeye Tuna", "Yellowfin Tuna", "Grouper", "Snapper"],
    },
    {
        "id": "pfz-wadge-trawl-flat",
        "name": "Wadge Bank High-Yield Trawl Flat",
        "lat": 7.6255,
        "lng": 77.5150,
        "harbour": "Chinnamuttam Harbour (68m Depth)",
        "dist": 37.0,
        "chl": 3.35,
        "sst": 27.6,
        "species": ["Deepwater Snapper", "Grouper", "Cuttlefish", "Carangids"],
    },
    {
        "id": "pfz-wadge-western-terrace",
        "name": "Wadge Bank Western Terrace",
        "lat": 7.5850,
        "lng": 77.0855,
        "harbour": "Chinnamuttam Harbour (75m Depth)",
        "dist": 39.0,
        "chl": 3.15,
        "sst": 27.7,
        "species": ["Cobia", "Amberjack", "King Mackerel", "Squid"],
    },
    {
        "id": "pfz-wadge-southwest-dropoff",
        "name": "Wadge Bank Southwest Drop-off",
        "lat": 7.4655,
        "lng": 77.2650,
        "harbour": "Chinnamuttam Deep Sea (110m Depth)",
        "dist": 44.5,
        "chl": 2.95,
        "sst": 27.5,
        "species": ["Yellowfin Tuna", "Bigeye Tuna", "Wahoo", "Barracuda"],
    },
    {
        "id": "pfz-wadge-south-trench",
        "name": "Wadge Bank South Oceanic Trench",
        "lat": 7.3150,
        "lng": 77.3855,
        "harbour": "Chinnamuttam Deep Sea (480m Depth)",
        "dist": 52.0,
        "chl": 2.70,
        "sst": 27.3,
        "species": ["Swordfish", "Bigeye Tuna", "Blue Marlin", "Deepwater Snapper"],
    },
    {
        "id": "pfz-wadge-abyssal-plain",
        "name": "Wadge Bank Abyssal Plain Edge",
        "lat": 7.2255,
        "lng": 77.5650,
        "harbour": "Chinnamuttam Deep Sea (850m Depth)",
        "dist": 58.5,
        "chl": 2.40,
        "sst": 27.1,
        "species": ["Swordfish", "Blue Marlin", "Skipjack", "Bigeye Tuna"],
    },

    # -------------------------------------------------------------
    # 18. ARABIAN SEA MARGIN (KANYAKUMARI DISTRICT)
    # -------------------------------------------------------------
    {
        "id": "pfz-muttom-rocky-headland",
        "name": "Muttom Point Rocky Headland",
        "lat": 8.1255,
        "lng": 77.3150,
        "harbour": "Colachel Harbour (22m Depth)",
        "dist": 4.5,
        "chl": 2.70,
        "sst": 28.2,
        "species": ["Yellowfin Tuna", "Rock Cod", "Trevally", "Lobster"],
    },
    {
        "id": "pfz-colachel-roadstead",
        "name": "Colachel Fishing Harbour Roadstead",
        "lat": 8.1750,
        "lng": 77.2455,
        "harbour": "Colachel Harbour (26m Depth)",
        "dist": 3.8,
        "chl": 2.65,
        "sst": 28.1,
        "species": ["Kingfish", "Skipjack Tuna", "Trevally", "Cuttlefish"],
    },
    {
        "id": "pfz-colachel-margin",
        "name": "Colachel Continental Margin",
        "lat": 8.1155,
        "lng": 77.1050,
        "harbour": "Colachel Harbour (68m Depth)",
        "dist": 11.2,
        "chl": 2.50,
        "sst": 28.0,
        "species": ["Yellowfin Tuna", "Skipjack", "Carangids", "Squid"],
    },
    {
        "id": "pfz-enayam-reef",
        "name": "Enayam Marine Reef",
        "lat": 8.2250,
        "lng": 77.1955,
        "harbour": "Colachel Harbour (24m Depth)",
        "dist": 5.0,
        "chl": 2.60,
        "sst": 28.1,
        "species": ["Snapper", "Grouper", "Seer Fish", "Shrimp"],
    },
    {
        "id": "pfz-thengapattinam-bar",
        "name": "Thengapattinam Estuary Bar",
        "lat": 8.2455,
        "lng": 77.1650,
        "harbour": "Thengapattinam Port (18m Depth)",
        "dist": 3.6,
        "chl": 2.85,
        "sst": 28.3,
        "species": ["Silver Pomfret", "Mullet", "Tiger Prawn", "Indian Salmon"],
    },
    {
        "id": "pfz-thengapattinam-offshore",
        "name": "Thengapattinam Offshore Bank",
        "lat": 8.1850,
        "lng": 76.9955,
        "harbour": "Thengapattinam Port (120m Depth)",
        "dist": 16.5,
        "chl": 2.30,
        "sst": 27.9,
        "species": ["Yellowfin Tuna", "Skipjack Tuna", "Barracuda", "Cobia"],
    },
    {
        "id": "pfz-arabian-tuna-trench",
        "name": "Arabian Sea Outer Tuna Trench",
        "lat": 8.0455,
        "lng": 76.9250,
        "harbour": "Colachel Deep Sea (340m Depth)",
        "dist": 28.0,
        "chl": 2.10,
        "sst": 27.7,
        "species": ["Swordfish", "Bigeye Tuna", "Sailfish", "Mahi Mahi"],
    },
]

print("Total scattered authentic fishing areas:", len(SCATTERED_FISHING_AREAS))
